name: CoreS
version: '1.0'
api-version: 1.19
author: WeedlyLife
main: me.weedlylife.cores.CoreS
commands:
  ping:
    description: show your ping or from a player.
  sit:
    description: makes u sit :).